"""
Export the OzFish benchmark (our leakage-safe split) into the input format the
MATANet official repo expects, so C08 runs THEIR model on OUR split.

Writes, into --out_dir:
    dataset_train.json   COCO-style: our TRAIN split (categories + annotations)
    dataset_test.json    COCO-style: our TEST split (the held-out eval set)
    hierarchical_label.csv   3-level (Family/Genus/Species) encoded, indexed by
                             0-based category id  (their sub_h loss reads this)
    dist_categories.csv      species-name NxN tree-distance matrix (their hier.
                             distance regulariser reads this)
    hierarchical_labelencoder.pkl   {id2name, name2id} per level
    ozfish_meta.json         nclass + per-level node counts (fills their config)

Design notes:
  - The split is baked INTO the JSONs: dataset_train.json holds only our train
    split, dataset_test.json only our test. So MATANet never sees test during
    training and we never touch their random-split code — the leakage-safe split
    is enforced by construction. (Our val is held out entirely; their B1 samples
    its own monitoring val from train.)
  - Each annotation carries a resolved absolute `image_path`, so multi-folder
    datasets work without symlinks (their datautils is patched to use it).
  - Taxonomy is 3-level to match our HSLM exactly (fair comparison; see paper).
  - category ids are 1-based in the JSON (their loader subtracts 1 -> 0..295);
    hierarchical_label.csv is indexed 0..295 to match.
"""

import argparse
import hashlib
import json
import os
import pickle
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from bioreef.config import BenchmarkConfig, DEFAULT_CONFIG_PATH
from bioreef.data import split_from_config, get_taxonomy_tree

RANKS = ["Family", "Genus", "Species"]   # 3-level, matches our HSLM


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--config", default=DEFAULT_CONFIG_PATH, help="benchmark config YAML")
    p.add_argument("--csv", default=None, help="override config data.csv_path")
    p.add_argument("--img_dir", default=None, help="override config data.img_dir")
    p.add_argument("--out_dir", default="matanet/ozfish_data",
                   help="where to write the MATANet input files")
    p.add_argument("--seed", type=int, default=0,
                   help="seed_number baked into the generated MATANet config")
    return p.parse_args()


def write_config(out_dir, nclass, node_cnt, seed):
    """Write the OzFish MATANet config (their experiment-final14 adapted).
    3-level Family/Genus/Species hierarchy; DINOv2-large fine-tuned (as published);
    logging disabled (no wandb). Paths point at the exported files (absolute)."""
    ad = os.path.abspath(out_dir)
    project = f"ozfish_matanet_seed{seed}"
    cfg = f"""# MATANet on the OzFish benchmark (generated by matanet/export_ozfish.py).
# Their experiment-final14 adapted to our leakage-safe split + 3-level taxonomy.
project_name: '{project}'
project_desc: 'MATANet (DINOv2-large, MCEAM, hierarchical) on OzFish deployment-grouped split'
device_num: [0]
device: 'cuda'
disable_logger: true          # no wandb
logger_id: null
trained_model_name: null
seed_number: {seed}
batch_size: 16
num_workers: 8
max_epochs: 60
scheduler_eta_max: 0.000001
scheduler_t_up: 5
scheduler_step_size: 30
scheduler_gamma: 0.5
lr: 0.000001
weight_decay: 0.001
accumulate_grad_batches: 1
phase: 'train'

# model — DINOv2-large fine-tuned (MATANet as published; the paper's fairness caveat)
obj_vit_encoder_path: 'facebook/dinov2-large'
img_vit_encoder_path: 'facebook/dinov2-large'
feature_dim: 1024

# data (OzFish exported inputs)
train_anno_path: '{ad}/dataset_train.json'
test_anno_path: '{ad}/dataset_test.json'
categories_path: '{ad}/dist_categories.csv'
nclass: {nclass}
kfold: false
kfold_nsplits: 1
obj_encoder_size: [256, 256]
img_encoder_size: [[256, 256]]
object_crop: 'square'
transform: true
img_downsampling: true
env_img_crop: true
env_img_crop_scale_list: [3, 5, -1]

# model options
intra_env_attn: true
hierarchical_loss: true

# hierarchy — 3 levels (Family/Genus/Species), matching our HSLM
hierarchical_node_cnt: {node_cnt}
hierarchical_node_rank: ['Family', 'Genus', 'Species']
hierarchical_label_path: '{ad}/hierarchical_label.csv'
hierachical_labelencoder_path: '{ad}/hierarchical_labelencoder.pkl'

# lambda
lambda_sub_h: 1.0
lambda_ce: 1.0

# where the trained checkpoint lands / test predictions go (patched B1/C1)
trained_ckpt_path: 'logs/{project}/Fold-0/last.ckpt'
submission_path: '{ad}/predictions_seed{seed}.csv'
"""
    path = os.path.join(out_dir, f"ozfish_config_seed{seed}.yaml")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(cfg)
    print(f"[export] wrote MATANet config -> {path}")


def image_id_of(img_path):
    """MATANet loads `{image_id}.png`; use the filename stem so it round-trips.
    (We also store the full resolved path in the annotation for robustness.)"""
    return os.path.splitext(os.path.basename(img_path))[0]


def _stable_ann_id(s):
    """Deterministic integer id derived from the crop's identity (file_name +
    bbox), NOT its position in the sample list. `enumerate(samples)` gave ids
    that shift whenever the split/filtering/ordering changes, so an old
    prediction file could silently score against a different fish. This id is
    reproducible across exports of the same crop."""
    fn = os.path.basename(s["img_path"])
    x, y, w, h = (int(b) for b in s["bbox"])
    key = f"{fn}|{x},{y},{w},{h}"
    # 63-bit stable hash of the key (md5 is deterministic across runs/machines,
    # unlike Python's salted hash()).
    return int(hashlib.md5(key.encode()).hexdigest()[:15], 16)


def coco_json(samples, categories):
    """Build a COCO-style dict from our split samples. category_id is 1-based
    (their loader subtracts 1). bbox is [x, y, w, h] (our native format).
    annotation `id` is a STABLE hash of file_name+bbox, so a prediction file
    stays joinable even if the export is regenerated in a different order."""
    annotations = []
    seen = {}
    for s in samples:
        aid = _stable_ann_id(s)
        if aid in seen and seen[aid] != s["img_path"]:
            raise SystemExit(
                f"[export] annotation id collision: {aid} maps to both "
                f"{seen[aid]} and {s['img_path']}. Two crops share file_name+bbox."
            )
        seen[aid] = s["img_path"]
        annotations.append({
            "id": aid,
            "image_id": image_id_of(s["img_path"]),
            "image_path": os.path.abspath(s["img_path"]),  # patched loader reads this
            "category_id": s["class_idx"] + 1,              # 1-based
            "bbox": [int(b) for b in s["bbox"]],            # [x, y, w, h]
        })
    return {"categories": categories, "annotations": annotations}


def tree_distance(sp_a, sp_b, tree):
    """3-level tree hop distance between two species (MATANet BiologicalTree
    semantics): same species 0, same genus 2, same family 4, else 6."""
    if sp_a == sp_b:
        return 0
    ta, tb = tree.get(sp_a), tree.get(sp_b)
    if ta is None or tb is None:
        return 6
    if ta["genus"] == tb["genus"]:
        return 2
    if ta["family"] == tb["family"]:
        return 4
    return 6


def main():
    args = parse_args()
    bench = BenchmarkConfig.from_yaml(args.config).apply_overrides(
        csv_path=args.csv, img_dir=args.img_dir,
    )
    if not bench.csv_path:
        raise SystemExit("no dataset CSV: set data.csv_path in the config or pass --csv")
    os.makedirs(args.out_dir, exist_ok=True)

    train_s, val_s, test_s, num_classes, idx_to_sp, _spc = split_from_config(
        bench.csv_path, bench.img_dir, bench,
    )
    tree = get_taxonomy_tree(bench.csv_path)
    species = [idx_to_sp[i] for i in range(num_classes)]           # index order = class_idx
    print(f"[export] {num_classes} species | train {len(train_s)} test {len(test_s)} "
          f"(val {len(val_s)} held out)")

    # --- COCO categories (1-based ids) + the two split JSONs -------------------
    categories = [{"id": i + 1, "name": sp} for i, sp in enumerate(species)]
    with open(os.path.join(args.out_dir, "dataset_train.json"), "w") as f:
        json.dump(coco_json(train_s, categories), f)
    with open(os.path.join(args.out_dir, "dataset_test.json"), "w") as f:
        json.dump(coco_json(test_s, categories), f)

    # --- hierarchical_label.csv (0-based category id -> encoded Family/Genus/Species)
    import pandas as pd
    from sklearn.preprocessing import LabelEncoder

    fam = [tree.get(sp, {}).get("family", "__unknown_family__") for sp in species]
    gen = [tree.get(sp, {}).get("genus", "__unknown_genus__") for sp in species]
    cols = {"Family": fam, "Genus": gen, "Species": species}

    encoded, id2name, name2id, node_cnt = {}, {}, {}, []
    for rank in RANKS:
        le = LabelEncoder()
        codes = le.fit_transform(cols[rank])
        encoded[rank] = codes
        id2name[rank] = {int(c): n for c, n in zip(codes, cols[rank])}
        name2id[rank] = {n: int(c) for c, n in zip(codes, cols[rank])}
        node_cnt.append(int(len(le.classes_)))

    hlabel = pd.DataFrame(encoded, columns=RANKS)
    hlabel.index = range(num_classes)                              # 0-based category id
    hlabel.to_csv(os.path.join(args.out_dir, "hierarchical_label.csv"))

    with open(os.path.join(args.out_dir, "hierarchical_labelencoder.pkl"), "wb") as f:
        pickle.dump({"id2name": id2name, "name2id": name2id}, f)

    # --- dist_categories.csv (species-name NxN tree distance) ------------------
    dist = pd.DataFrame(0, index=species, columns=species, dtype=float)
    for i, a in enumerate(species):
        for j in range(i, num_classes):
            d = tree_distance(a, species[j], tree)
            dist.iloc[i, j] = d
            dist.iloc[j, i] = d
    dist.to_csv(os.path.join(args.out_dir, "dist_categories.csv"))

    # --- meta (fills the config: nclass + per-level node counts) ---------------
    meta = {"nclass": num_classes, "ranks": RANKS, "node_cnt": node_cnt,
            "n_train": len(train_s), "n_test": len(test_s)}
    with open(os.path.join(args.out_dir, "ozfish_meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

    # --- the MATANet config for OzFish (node_cnt is always correct this way) ---
    write_config(args.out_dir, num_classes, node_cnt, args.seed)

    print(f"[export] wrote MATANet inputs to {args.out_dir}/")
    print(f"  ranks={RANKS}  node_cnt={node_cnt}  (Family/Genus/Species)")
    print(f"  set the config with: nclass={num_classes}, "
          f"hierarchical_node_cnt={node_cnt}")


if __name__ == "__main__":
    main()
